# Documentation: https://roots.io/trellis/docs/vault/
vault_mail_password: smtp_password

vault_wordpress_sites:
    example.com:
        admin_password: admin
        env:
            db_password: example_dbpassword
