workflows:
    version: 2
    test_stage_prod:
        jobs:
            - test:
                docker:
                    - image: circleci/php:7.1.4-cli
                filters:
                    branches:
                        only:
                            - test
                working_directory: site
                steps:
                    - run: pip install ansible
                      # - run: npm install
                      # - run: composer install
                    - run: ../trellis/bin/deploy.sh test poc-test.rian.codes

            - qa-aproval:
                type: approval
                requires:
                    - test
            - stage:
                docker:
                    - image: circleci/php:7.1.4-cli
                filters:
                    branches:
                        only:
                            - stage
                requires:
                    - qa-approval
            - production:
                docker:
                    - image: circleci/php:7.1.4-cli
                filters:
                    branches:
                        only:
                            - test
# General config
#general:
#  build_dir: site
#
## Configure the machine
#machine:
#  timezone:
#      America/Los_Angeles
#  node:
#    version: 6.0.0
#  python:
#    version: 2.7.10
#
#dependencies:
#  pre:
#    - pip install ansible
#  override:
#    - npm install
#    - composer install
#
#test:
#  override:
#    - npm run test
#
## Deploy
#deployment:
#  staging:
#    branch: staging
#    commands:
#      - ../trellis/bin/deploy.sh staging example.com
