version: 2
jobs:
    test:
        docker:
            - image: circleci/php:7.1.4-cli
        filters:
            branches:
                only:
                    - test
        steps:
            - pip ansible install
            - run: ../trellis/bin/deploy.sh test poc-test.rian.codes
workflows:
    version: 2
    test_stage_prod:
        jobs:
            - test
            - push-test-code-to-staging:
                type: approval
                requires:
                    - test
            - push-test-db-to-staging:
                type: approval
                requires:
                    - test
# General config
#general:
#  build_dir: site
#
## Configure the machine
#machine:
#  timezone:
#      America/Los_Angeles
#  node:
#    version: 6.0.0
#  python:
#    version: 2.7.10
#
#dependencies:
#  pre:
#    - pip install ansible
#  override:
#    - npm install
#    - composer install
#
#test:
#  override:
#    - npm run test
#
## Deploy
#deployment:
#  staging:
#    branch: staging
#    commands:
#      - ../trellis/bin/deploy.sh staging example.com
