# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  poc-staging.rian.codes:
    site_hosts:
      - canonical: poc-staging.rian.codes
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:rianfowler/wordpress-ci-poc.git
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
